on: [issues, pull_request]
jobs:
  auto-close-lock_job:
    runs-on: ubuntu-latest
    name: Automatically closes and locks issues and pull requests
    steps:
    - name: auto-close-lock action step
      id: auto-close-lock
      uses: dinkypumpkin/auto-close-lock@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
